version: '3.9'

services:
  premonition:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: premonition_v3
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
    command: python main.py
