version: '3.8'

services:
  bot:
    build: .
    container_name: premonition_bot
    env_file: .env
    command: python main.py
    volumes:
      - .:/app
    restart: unless-stopped

  api:
    build: .
    container_name: premonition_api
    env_file: .env
    command: python api/app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    restart: unless-stopped
